#!/usr/bin/env perl

use strict;
use warnings;
use Web::API::Mock;
use Plack::Runner;

use Getopt::Long qw/GetOptions :config auto_help pass_through/;

GetOptions(\my %options, qw/
    files=s@
/);

my $mock = Web::API::Mock->new();
$mock->setup($options{files});
my $app = $mock->psgi();

my $runner = Plack::Runner->new;
$runner->parse_options(@ARGV);
$runner->run($app)

__END__

=encoding utf-8

=head1 NAME

run-api-mock - It's Plack Server

=head1 SYNOPSIS

    $ run-api-mock -f api1.md -f api2.md
     :
    $ run-api-mock --files api.md --port 8080

=cut

